# Generated by Django 5.2.14 on 2026-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_tj',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_tj',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_tj',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_tj',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
