# Generated by Django 5.2 on 2026-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
