# Generated by Django 5.2 on 2026-08-09 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('num_questions', models.PositiveIntegerField(default=10)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('tj', 'Tajik'), ('en', 'English')], default='en', max_length=2)),
                ('questions_data', models.JSONField(default=list)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_detailed_analysis', models.JSONField(default=dict)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
