# Generated by Django 5.2 on 2026-08-16 09:01

from django.db import migrations


from django.utils.text import slugify

def populate_quiz_slugs(apps, schema_editor):
    Quiz = apps.get_model('quiz', 'Quiz')
    for quiz in Quiz.objects.all():
        if not quiz.slug:
            base = slugify(quiz.title, allow_unicode=True) or "quiz"
            unique_slug = base
            counter = 1
            while Quiz.objects.filter(slug=unique_slug).exclude(pk=quiz.pk).exists():
                unique_slug = f"{base}-{counter}"
                counter += 1
            quiz.slug = unique_slug
            quiz.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_slug'),
    ]

    operations = [
        migrations.RunPython(populate_quiz_slugs, reverse_code=migrations.RunPython.noop),
    ]
