# Generated by Django 5.2 on 2026-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('tj', 'Tajik'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
