# Generated by Django 5.2 on 2026-08-16 09:01

from django.db import migrations


from django.utils.text import slugify

def populate_course_slugs(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        if not course.slug:
            base = slugify(course.title, allow_unicode=True) or "course"
            unique_slug = base
            counter = 1
            while Course.objects.filter(slug=unique_slug).exclude(pk=course.pk).exists():
                unique_slug = f"{base}-{counter}"
                counter += 1
            course.slug = unique_slug
            course.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_slug'),
    ]

    operations = [
        migrations.RunPython(populate_course_slugs, reverse_code=migrations.RunPython.noop),
    ]
